project:
  type: website
  render:
    - "*"
    - "!WARP.md"

website:
  title: "vz-logbook"
  navbar:
    background: light
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/vanzaj/vz-logbook.git
    search: true
  sidebar:
    style: "floating"
    collapse-level: 1
    contents: auto
 
format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    include-after-body: _goatcounter.html


