project:
  type: website
  render:
    - "*"
    - "!WARP.md"

website:
  title: "VZ's LogBook"
  description: "Vanzaj's personal internet corner. All opinions are mine."

  site-url: "https://sansans.net"
  repo-url: "https://github.com/vanzaj/vz-logbook"

  page-footer:
    left: |
      <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/"><img src="/assets/cc-by-nc-sa.png" alt="CC BY-NC-SA" style="height: 31px;"></a>
  
  page-navigation: true

  navbar:
    background: light
    title: "VZ's LogBook"
    left:
      - text: ""
    right:
      - text: ABOUT
        href: about.qmd
      - text: NOW
        href: now.qmd
      - text: TALKS
        href: talks/
      - text: NOTES
        menu:
          - text: Books
            href: notes/books/
          - text: Bots
            href: notes/bots/
          - text: Education
            href: notes/edu/
          - text: Published
            href: notes/pub/
          - text: Tech
            href: notes/tech/
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/vanzaj/vz-logbook.git
    search: true
 
format:
  html:
    theme: yeti
    css: custom.css
    toc: true
    include-after-body: _goatcounter.html

